version: '3'

tasks:
  default:
    desc: "Show all tasks"
    cmd: task --list

  init:
    desc: "Initialize project"
    cmds:
      - python setup/exec.py

  fmt:
    desc: "Run Ruff"
    cmds:
      - ruff format .
      - ruff check --fix

  test-all:
    desc: "Run all tests"
    cmds:
      - pytest

  test:
    desc: "Run tests excluding those marked as 'slow' or 'view'"
    cmds:
      - pytest -m "not slow and not view" -s
