version: '3'

tasks:
  default:
    desc: "Show all tasks"
    cmd: task --list

  init:
    desc: "Initialize project"
    cmds:
      - python setup/data_prepare.py

  fmt:
    desc: "Run Ruff"
    cmds:
      - ruff format .
      - ruff check --fix

  test:
    desc: "Run all tests"
    cmds:
      - pytest

  test-short:
    desc: "Run tests excluding those marked as 'slow'"
    cmds:
      - pytest -m "not slow"
